#pragma once

#include "platform.h"

#define ACTIVITY_MAXARGS 100
#define ACTIVITY_SEPARATOR "/"
#define ACTIVITY_FILESTRING "FILE"
#define ACTIVITY_TRANSCOSTRING "TRANSCOEF"
#define ACTIVITY_SAMPLESTRING "SAMPLE"
#define ACTIVITY_TRIGGERSTRING "TRIGGER"
#define ACTIVITY_ACTIVITYSTRING "Activities"
#define ACTIVITY_FILESUFFIX "ae"
